public class cc_ktp_OrderProcessor {
	/***Create a Method for the following  
	1.Place Order
	2.Get Person details(Need a SOQL based on the orderId)
	3.GetOrder Details(Need a SOQL based on the orderId)
	4.Shipping information
	5.Address Information
	6.Order Item information
	7.Handle Discounts
	8.Pricing Informations
	9.Payment Information
	We can have multiple orders for one single person***/
	public static void placeOrder(String OrderId){
		
	}
	
    public static ktp_GR_OrderDO createOrderDO(String OrderId){
       
       return null;
    }
    public static ktp_GR_PersonDO createPersonDO(String OrderId){
    	return null;
    }   
    }