/******************************************************************************
** Module Name   : KapCommonVOTest
** Description   : A Value Object (VO) used to entity to hold relationship data
** 
** Technial Info : <Classes, Methods, etc>
** 
** Author(s)     : Chaitanya Katragadda() - Kaplan
** Revision History:-
** Version  Date    Author  Description of Action
** 1.0    04/26/2011       Initiated Script
******************************************************************************/

@isTest
private class KapCommonVOTest {

    static testMethod void testKapGetRealAddressVO() {
        KapGetRealAddressVO relAddVO = new KapGetRealAddressVO();
    }
    
    static testMethod void testKapGetRealEmailVO() {
        KapGetRealEmailVO relEmailVO = new KapGetRealEmailVO();
    }
    
    static testMethod void testKapGetRealInteractionVO() {
        KapGetRealInteractionVO relInterVO = new KapGetRealInteractionVO();
    }
    
    static testMethod void testKapGetRealInternationalInfoVO() {
        KapGetRealInternationalInfoVO relInterInfoVO = new KapGetRealInternationalInfoVO();
    }
    
    static testMethod void testKapGetRealPersonVO() {
        KapGetRealPersonVO relPersonVO = new KapGetRealPersonVO();
    }
    
    static testMethod void testKapGetRealPhoneVO() {
        KapGetRealPhoneVO relPhoneVO = new KapGetRealPhoneVO();
    }
    
    static testMethod void testKapGetRealRelationshipVO() {
        KapGetRealRelationshipVO relRelationVO = new KapGetRealRelationshipVO();
    }
    
    static testMethod void testKapGetRealExclusionVO() {
        KapGetRealExclusionVO relExclusionVO = new KapGetRealExclusionVO();
    }
    
    
}