/******************************************************************************
** Module Name   : KapGetRealEmailVO
** Description   : A Value Object (VO) used to entity to hold email data
** 
** Technial Info : <Classes, Methods, etc>
** 
** Author(s)     : George Koodarappally (GK) - Acumen Solutions
** Revision History:-
** Version	Date		Author	Description of Action
** 1.0		03/01/2011	GK 		Initiated Script
******************************************************************************/

public with sharing class KapGetRealEmailVO {
    public String index {get; set;}
    public String email_address {get; set;}

    /*
    public String XX {get; set;}
    public String XX {get; set;}
    */
}